-- ========================
-- BẢNG USERS
-- ========================
CREATE TABLE "users" (
    "user_id" VARCHAR(15) PRIMARY KEY,
    "password" VARCHAR(255) NOT NULL,
    "role" VARCHAR(15) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "date_of_birth" DATE,
    "mail" VARCHAR(100) NOT NULL,
    "phone" VARCHAR(10) NOT NULL UNIQUE,
    "address" VARCHAR(255),
    "gender" VARCHAR(6) CHECK (gender IN ('male', 'female', 'other')),
    "creation_time" TIMESTAMP NOT NULL
);
COMMENT ON COLUMN users.phone IS 'chỉ có 1sdt cho 1 tk';

-- ========================
-- BẢNG COMMENTS
-- ========================
CREATE TABLE "comments" (
    "comment_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" VARCHAR(15) NOT NULL,
    "contents" VARCHAR(255) NOT NULL,
    "creation_time" TIMESTAMP NOT NULL,
    "parent_id" INTEGER
);
COMMENT ON COLUMN comments.parent_id IS 'Nếu null: đây là bình luận gốc. Nếu chứa id của một bình luận khác: đây là trả lời (reply) cho bình luận đó.';

-- ========================
-- BẢNG COMMENT REACTIONS
-- ========================
CREATE TABLE "comment_reactions" (
    "reaction_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" VARCHAR(15) NOT NULL,
    "comment_id" INTEGER NOT NULL,
    "reaction_type" VARCHAR(10) NOT NULL CHECK (reaction_type IN ('like', 'haha', 'sad', 'wow')),
    "created_at" TIMESTAMP NOT NULL,
    UNIQUE(user_id, comment_id)
);

-- ========================
-- BẢNG REPORT
-- ========================
CREATE TABLE "report" (
    "report_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "reporter_id" VARCHAR(15) NOT NULL,
    "target_type" VARCHAR(255) NOT NULL,
    "target_id_str" VARCHAR(255),
    "target_id_int" INTEGER,
    "reason" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL
);
COMMENT ON COLUMN report.target_type IS 'Kiểu đối tượng bị báo cáo, ví dụ: ''comment'', ''user''';
COMMENT ON COLUMN report.target_id_str IS 'ID của đối tượng bị báo cáo (dạng chuỗi)';
COMMENT ON COLUMN report.target_id_int IS 'ID của đối tượng bị báo cáo (dạng số nguyên)';

-- ========================
-- BẢNG CATEGORIES
-- ========================
CREATE TABLE "categories" (
    "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(60) NOT NULL,
    "slug" VARCHAR(255) NOT NULL UNIQUE
);

-- ========================
-- BẢNG SUB-CATEGORIES
-- ========================
CREATE TABLE "sub_categories" (
    "sub_category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category_id" INTEGER NOT NULL,
    "name" VARCHAR(60) NOT NULL,
    "slug" VARCHAR(255) NOT NULL UNIQUE
);

-- ========================
-- BẢNG POSTS
-- ========================
CREATE TABLE "posts" (
    "post_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(255) NOT NULL,
    "slug" VARCHAR(255) NOT NULL UNIQUE,
    "content" TEXT NOT NULL,
    "author_id" VARCHAR(15) NOT NULL,
    "category_id" INTEGER NOT NULL,
    "sub_category_id" INTEGER NOT NULL,
    "status" VARCHAR(20) NOT NULL CHECK (status IN ('draft', 'published', 'archived')),
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP,
    "views_count" INTEGER NOT NULL DEFAULT 0,
    "is_featured" BOOLEAN DEFAULT FALSE
);
COMMENT ON COLUMN posts.status IS 'Trạng thái bài viết: draft, published, archived.';

-- ========================
-- BẢNG POST_TAGS
-- ========================
CREATE TABLE "post_tags" (
    "post_id" INTEGER NOT NULL,
    "tag" VARCHAR(255) NOT NULL,
    PRIMARY KEY(post_id, tag)
);

-- ========================
-- BẢNG SAVE_POSTS
-- ========================
CREATE TABLE "save_posts" (
    "user_id" VARCHAR(15) NOT NULL,
    "post_id" INTEGER NOT NULL,
    "saved_at" TIMESTAMP NOT NULL,
    PRIMARY KEY(user_id, post_id)
);

-- ========================
-- BẢNG IMAGES
-- ========================
CREATE TABLE "images" (
    "image_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "url" VARCHAR(255) NOT NULL,
    "target_type" VARCHAR(255) NOT NULL,
    "target_id_int" INTEGER,
    "target_id_str" VARCHAR(15),
    "is_thumbnail" BOOLEAN DEFAULT FALSE,
    "uploaded_at" TIMESTAMP NOT NULL
);
COMMENT ON COLUMN images.target_type IS 'Kiểu đối tượng: user, category, sub_category, post...';
COMMENT ON COLUMN images.target_id_int IS 'Dùng nếu đối tượng là post, category,...';
COMMENT ON COLUMN images.target_id_str IS 'Dùng nếu đối tượng là user,...';

-- ========================
-- KHÓA NGOẠI
-- ========================
ALTER TABLE "comments"
ADD FOREIGN KEY("user_id") REFERENCES "users"("user_id");

ALTER TABLE "comments"
ADD FOREIGN KEY("parent_id") REFERENCES "comments"("comment_id");

ALTER TABLE "comment_reactions"
ADD FOREIGN KEY("user_id") REFERENCES "users"("user_id");

ALTER TABLE "comment_reactions"
ADD FOREIGN KEY("comment_id") REFERENCES "comments"("comment_id");

ALTER TABLE "report"
ADD FOREIGN KEY("reporter_id") REFERENCES "users"("user_id");

ALTER TABLE "sub_categories"
ADD FOREIGN KEY("category_id") REFERENCES "categories"("category_id");

ALTER TABLE "posts"
ADD FOREIGN KEY("author_id") REFERENCES "users"("user_id");

ALTER TABLE "posts"
ADD FOREIGN KEY("category_id") REFERENCES "categories"("category_id");

ALTER TABLE "posts"
ADD FOREIGN KEY("sub_category_id") REFERENCES "sub_categories"("sub_category_id");

ALTER TABLE "post_tags"
ADD FOREIGN KEY("post_id") REFERENCES "posts"("post_id");

ALTER TABLE "save_posts"
ADD FOREIGN KEY("user_id") REFERENCES "users"("user_id");

ALTER TABLE "save_posts"
ADD FOREIGN KEY("post_id") REFERENCES "posts"("post_id");
